import strings
import files
import strings.stringDoc

title = """
# Python Data Structures

Learning Python data structures. this document is generated by code itself I hope you enjoy it.
"""
stringsSection = strings.stringDoc.section 
filesSection = files.section
footer = """
## Credits

**Ismael Varela**, Fulstack Developer
"""
content = title 
content += stringsSection
content += filesSection
content += footer

files.writeToFile(content)

print("\nDone By Ismael Varela.\n")
