import dictionaries
import lists
import strings
import files
import strings.stringDoc
import tuples

fileName = "README.md"
title = """
# Python Data Structures

Learning Python data structures. this document is generated by code itself I hope you enjoy it.
"""
stringsSection = strings.stringDoc.section 
fileLines = files.readFile(fileName)
filesSection = files.getSectionContent(fileLines, files.preContent, files.subContent)
sortedList = tuples.sortDictByValue(tuples.wordCount(fileLines))
footer = """
## Credits

**Ismael Varela**, Fulstack Developer
"""
content = title 
content += stringsSection
content += filesSection
content += lists.section
content += dictionaries.section
content += tuples.section
content += tuples.printWordsCount(sortedList[:10])
content += footer

files.writeToFile(fileName, content)

print("\nDone By Ismael Varela.\n")